### ISSUE TITLE
Game does not terminate after closing tab forcefully

### ISSUE THREAD

**Issue by QinCai-rui** [webdev03/maths#4]
Another bug. When the host closes the tab 'host page' without clicking the end game button, the game would not end and will be still ran on the server. I think it might be a problem when people tries to do it on purpose, which would yeah, y'know.

**Comment by imdevarsh** [comment]
This is intentional; the host should be able to reload or share the link with someone else. The link required should be in the browser history. If that feature is broken on our side, then it is a bug.

**Comment by imdevarsh** [comment]
Or are you suggesting that I should remove this so that memory doesn't keep on building up?

**Comment by QinCai-rui** [comment]
The thing is if people started to do this on purpose, it could become a real issue. Maybe add a timeout like 30 mins?
